name: MaxBansPlus
version: ${version}
main: org.maxgamer.maxbans.MaxBansPlus
description: "Advanced banning and muting plugin allowing for some better management of misbehaved players."
author: netherfoam

commands:
   ban:
      description: Bans a user, optionally for a duration
      usage: /ban <user> [duration] [message]

   ipban:
      description: Bans an IP address, optionally for a duration
      usage: /ipban <user|ip> [duration] [message]

   unban:
      description: Unbans a user
      usage: /unban <user>

   mute:
      description: Mutes a user, optionally for a duration
      usage: /mute <user> [duration] [message]

   ipmute:
      description: Mutes an IP address, optionally for a duration
      usage: /ipmute <user|ip> [duration] [message]

   unmute:
      description: Unmutes a user
      usage: /unmute <user>

   kick:
      description: Kicks a user
      usage: /kick <player> [message]

   checkban:
      description: Inspect information about a players most recent IP address, ban and mute status
      usage: /checkban <user>
      aliases: ["lookup", "iplookup", "dupeip"]

   warn:
      description: Warn a player for misbehaviour
      usage: /warn <user> [message]

   lockdown:
      description: Prevent players from joining the server.
      usage: /lockdown <ALL|JOIN|NEW|OFF> [reason]

   history:
      description: View the recent punishments dealt to players through MaxBans Plus
      usage: /history [moderator] [page]

permissions:
   maxbans.ban:
      description: Use the /ban and /unban commands

   maxbans.mute:
      description: Use the /mute and /unmute commands

   maxbans.lockdown:
      description: Use the /lockdown command

   maxbans.iplookup:
      description: Use the /iplookup command

   maxbans.kick:
      description: Use the /kick command

   maxbans.warn:
      description: Use the /warn command

   maxbans.history:
      description: Use the /history command

   maxbans.silent:
      description: See command announcements even when they're silenced using the -s flag

   maxbans.broadcast:
      description: See broadcasted messages
      default: true

   maxbans.mod:
      description: See moderator only messages such as alerts when banned players try to join
